### ISSUE TITLE
moving to /new or /best has the page stuck on spinner. posts aren't showing on route changes?

### ISSUE THREAD

**Issue by topaztee** [dpraburaj/react-microscope#1]
Any idea why?

**Comment by topaztee** [comment]
Any idea why?

**Comment by dpraburaj** [comment]
Hi,

I'm not quite sure why that's happening. Are you getting the spinner locally or on the demo page?

**Comment by topaztee** [comment]
locally. I ended up just removing the spinner altogether; for now.

**Comment by dpraburaj** [comment]
This issue is fixed in the latest version of react-spin. If anyone else is facing this issue, please try upgrading react spin(dpraburaj:react-spin@=2.3.4) and running the app again.
